/**
 * Config Builder - 从表单中间态（BackendEntry）构建 Centag 配置
 * 共享模块：WebUI（ES import）使用；打包导出在「后端网关配置」页完成
 *
 * 与 provider-form.js 分工：
 *   - provider-form：共用「选预设→填表→校验→中间态」流程
 *   - ConfigBuilder：把中间态序列化为 YAML / zip（initdata 打包）
 *   - Gateway 持久化走 toApiBackendPayload → /api/v1/backends → DB，不经本文件写盘
 *
 * 依赖：provider-registry.js (getProviderById), yaml-writer.js (YamlWriter)
 */
class ConfigBuilder {
  /**
   * Pipeline 模板 YAML 数据集
   * 占位符 $DEFAULT_BACKEND / $DEFAULT_MODEL 在导出时替换为用户的默认后端 ID 和默认模型
   */
  static PIPELINE_TEMPLATES_DATA = {
    'direct-backend': `id: direct-backend
name: 直连后端
shortcut_code: '#d'
description: 'Minimal 默认模式：所有请求直发配置的 LLM 后端，最简链路'
version: '1.0'
nodes:
- id: generate
  type: generator
  kind: llm.generate
  implementation: builtin.generator
  name: 直连生成
  backend: $DEFAULT_BACKEND
  model: $DEFAULT_MODEL
  config:
    prompt_template: '{{input}}'
    system_prompt: 你是可靠助手，请直接、准确地回答用户问题。
  timeout: 120
  retry:
    max_attempts: 0
    backoff_strategy: exponential
    initial_delay: 1000
    max_delay: 30000
global_config:
  timeout: 120
  max_retries: 3
  bypass_on_error: true
  parallel_limit: 4
  log_level: info
metadata:
  aligned_proxy_mode: direct-backend
  profile: minimal
  lastUpdated: '2026-07-13T00:00:00.000Z'
  layoutVersion: '1.1'`,
    'transparent-fast': `id: transparent-fast
name: 超快透明代理
description: 最速无缓存透明 HTTP 转发——单节点直连上游 API
version: "1.0"
shortcut_code: '#tf'
nodes:
- id: forward
  type: transparent_forward
  kind: proxy.transparent_forward
  implementation: builtin.transparent_forward
  name: 透明转发
  backend: $DEFAULT_BACKEND
  model: $DEFAULT_MODEL
  config:
    backend: $DEFAULT_BACKEND
    model: $DEFAULT_MODEL
    custom_config:
      default_scheme: https
  timeout: 120
  retry:
    max_attempts: 0
    backoff_strategy: exponential
    initial_delay: 1000
    max_delay: 30000
global_config:
  timeout: 120
  max_retries: 0
  bypass_on_error: false
  parallel_limit: 1
  log_level: info
metadata:
  aligned_proxy_mode: transparent-fast
  profile: minimal
  features:
    - transparent_forward
    - raw_passthrough
    - zero_cache
  lastUpdated: '2026-07-13T00:00:00.000Z'
  layoutVersion: '1.1'
  template_scope: mode-id-alignment`,
  }

  /**
   * 获取默认后端的 ID 和模型
   * @param {Array} backends
   * @returns {{ backendId: string, model: string }}
   */
  static getDefaultBackendInfo(backends) {
    const def = backends.find(b => b.isDefault) || backends[0]
    if (!def) return { backendId: 'openai', model: 'gpt-4o-mini' }
    return {
      backendId: def.provider.id,
      model: def.defaultModel || def.models?.[0]?.name || 'gpt-4o-mini',
    }
  }

  /**
   * 构建 initial-backends.yaml 内容
   * @param {Array} backends - 后端配置数组
   * @returns {string} YAML 字符串
   */
  static buildBackendsYaml(backends) {
    const data = {
      version: '2.0',
      description: 'Generated by Centag Backends export',
      backends: backends.map(b => this.buildSingleBackend(b)),
    }
    return YamlWriter.stringify(data)
  }

  /**
   * 构建单个后端配置
   * @param {Object} backend
   * @returns {Object}
   */
  static buildSingleBackend(backend) {
    const { provider, apiKey, models, settings } = backend
    const enabled = !!apiKey || provider.id === 'ollama'

    return {
      id: provider.id,
      name: provider.name,
      type: provider.type,
      base_url: provider.base_url,
      api_key: backend.apiKey || '',
      enabled: enabled,
      timeout: settings.timeout || 120,
      max_retries: settings.maxRetries || 3,
      auto_fetch_models: false,
      description: provider.description,
      supported_models: models.map(m => ({
        requested_model: m.name,
        actual_model: m.actual_model || m.name,
        is_exact: true,
        compatibility_score: 1.0,
      })),
      capabilities: {
        max_context_tokens: this.getMaxContextTokens(models),
        features: this.getFeatures(models),
        supports_tools: models.some(m => m.supports_tools),
      },
      weight: settings.weight || 100,
      priority: settings.priority || 10,
    }
  }

  /**
   * 获取最大上下文 Token 数
   * @param {Array} models
   * @returns {number}
   */
  static getMaxContextTokens(models) {
    if (models.length === 0) return 128000
    return Math.max(...models.map(m => m.max_context_tokens || 0))
  }

  /**
   * 获取特性列表
   * @param {Array} models
   * @returns {string[]}
   */
  static getFeatures(models) {
    const features = new Set(['chat', 'completion'])
    models.forEach(m => {
      if (m.supports_tools) features.add('function-calling')
      if (m.supports_images) features.add('vision')
    })
    return Array.from(features)
  }

  /**
   * 构建 .env 文件内容
   * @param {Array} backends
   * @returns {string}
   */
  static buildEnvContent(backends) {
    const lines = ['# Centag 环境变量配置', '# 请将以下内容添加到 .env 文件', '']
    backends.forEach(b => {
      if (b.apiKey) {
        const key = b.provider.env_key || `${b.provider.id.toUpperCase().replace(/-/g, '_')}_API_KEY`
        lines.push(`${key}=${b.apiKey}`)
      } else if (b.provider.env_key) {
        lines.push(`# ${b.provider.env_key}=`)
      }
    })
    return lines.join('\n')
  }

  /**
   * 构建使用说明
   * @returns {string}
   */
  static buildReadme() {
    return `# Centag 配置文件

## 文件说明

- \`initial-backends.yaml\` - 后端配置文件
- \`.env\` - 环境变量配置（API Key）

## 使用方法

1. 将 \`.env\` 文件中的 API Key 填写完整
2. 将 \`initial-backends.yaml\` 复制到对应的 profile 目录：
   - minimal: \`config/profiles/minimal/initdata/initial-backends.yaml\`
   - gateway: \`config/profiles/gateway/initdata/initial-backends.yaml\`
   - team: \`config/profiles/team/initdata/initial-backends.yaml\`
3. 启动 Centag

## 注意事项

- Ollama 本地服务不需要 API Key
- 修改配置后需要重启 Centag 生效
- 支持 OpenAI 兼容协议的 Provider 都可以选择 \`openai\` 类型
`
  }

  /**
   * 构建单个 Pipeline 模板 YAML（注入默认后端 ID 和模型）
   * @param {string} templateId - 模板 ID
   * @param {string} backendId - 默认后端 ID
   * @param {string} model - 默认模型名
   * @returns {string} YAML 字符串
   */
  static buildPipelineTemplateYaml(templateId, backendId, model) {
    const raw = this.PIPELINE_TEMPLATES_DATA[templateId]
    if (!raw) return ''
    return raw
      .replace(/\$DEFAULT_BACKEND/g, backendId)
      .replace(/\$DEFAULT_MODEL/g, model)
  }

  /**
   * 构建所有导出文件（flat map of path → content）
   * @param {Array} backends - 后端配置数组
   * @param {string[]} selectedTemplateIds - 选中的模板 ID 列表
   * @returns {Object<string, string>}
   */
  static buildAllYamlFiles(backends, selectedTemplateIds) {
    const { backendId, model } = this.getDefaultBackendInfo(backends)
    const files = {}
    files['initial-backends.yaml'] = this.buildBackendsYaml(backends)
    ;(selectedTemplateIds || []).forEach(id => {
      const yaml = this.buildPipelineTemplateYaml(id, backendId, model)
      if (yaml) {
        files[`pipeline-templates/${id}.yaml`] = yaml
      }
    })
    return files
  }

  /**
   * 导出 Archive（zip）
   * WebUI：动态 import('jszip')；classic script：globalThis.JSZip
   * @param {Array} backends
   * @param {string[]} selectedTemplateIds
   * @returns {Promise<Blob>}
   */
  static async exportAsArchive(backends, selectedTemplateIds) {
    const files = this.buildAllYamlFiles(backends, selectedTemplateIds)
    let JSZipCtor = typeof globalThis !== 'undefined' ? globalThis.JSZip : null
    if (!JSZipCtor) {
      const mod = await import('jszip')
      JSZipCtor = mod.default || mod
    }
    const zip = new JSZipCtor()
    Object.entries(files).forEach(([path, content]) => {
      zip.file(path, content)
    })
    return zip.generateAsync({ type: 'blob' })
  }
}

// UMD: 兼容 script 标签 (WebUI) 和 ES module (webui)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ConfigBuilder }
}

// classic script + provider-form 依赖解析用（class 声明默认不挂到 globalThis）
if (typeof globalThis !== 'undefined') {
  globalThis.ConfigBuilder = ConfigBuilder
}
