package backend

import (
	"os"

	"centag/core/pkg/logger"

	"gopkg.in/yaml.v3"
)

// FileBackendStore implements BackendStore using a YAML file.
// It is used by the minimal edition (no database).
type FileBackendStore struct {
	filePath string
}

// NewFileBackendStore creates a new FileBackendStore.
func NewFileBackendStore(filePath string) *FileBackendStore {
	return &FileBackendStore{filePath: filePath}
}

// Load reads all backend configs from the YAML file.
// If the file does not exist it returns an empty slice (not an error).
func (s *FileBackendStore) Load() ([]*BackendConfig, error) {
	data, err := os.ReadFile(s.filePath)
	if err != nil {
		if os.IsNotExist(err) {
			logger.Infof("Backend config file not found: %s, starting with empty list", s.filePath)
			return nil, nil
		}
		return nil, err
	}

	var fileCfg fileBackendsConfig
	if err := yaml.Unmarshal(data, &fileCfg); err != nil {
		return nil, err
	}

	backends := make([]*BackendConfig, 0, len(fileCfg.Backends))
	for _, fe := range fileCfg.Backends {
		backends = append(backends, fileEntryToBackendConfig(&fe))
	}

	logger.Infof("Loaded %d backends from file: %s", len(backends), s.filePath)
	return backends, nil
}

// Save writes all backend configs to the YAML file.
func (s *FileBackendStore) Save(backends []*BackendConfig) error {
	fileCfg := fileBackendsConfig{
		Version:     "2.0",
		Description: "Generated by Config Generator",
		Backends:    make([]fileBackendEntry, 0, len(backends)),
	}

	for _, b := range backends {
		fileCfg.Backends = append(fileCfg.Backends, backendConfigToFileEntry(b))
	}

	data, err := yaml.Marshal(fileCfg)
	if err != nil {
		return err
	}

	if err := os.WriteFile(s.filePath, data, 0644); err != nil {
		return err
	}

	logger.Infof("Saved %d backends to file: %s", len(fileCfg.Backends), s.filePath)
	return nil
}
