-- 024: Add API key limit columns (budget, rate limit, model whitelist) to api_keys.

ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS budget_usd DECIMAL(12,6) NOT NULL DEFAULT 0;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS used_usd DECIMAL(12,6) NOT NULL DEFAULT 0;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS rate_limit_rpm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS rate_limit_tpm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS model_whitelist TEXT NOT NULL DEFAULT '*';
